Feature/sdk 42 location
2gis/MapGL-Android pull request #17
Opened 2020-07-29 09:54 UTC by alexander-nsk

2020-07-30 04:34 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +import ru.dublgis.dgismobile.mapsdk.utils.location.UserLocationOptions
Зачем нужно слово utils? Логичным было бы - `ru.dublgis.dgismobile.mapsdk.location`.

2020-07-30 04:36 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +                permissionOptions = PermissionOptions(
В чем смысл `PermissionOptions`? Может не делать такой параметр, а в реализации всегда запрашивать тот, который нужен?

2020-07-30 04:38 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +        //locationProvider.onRequestPermissionsResult(requestCode, permissions, grantResults)
Мусорный комментарий, функцию можно удалить целиком.

2020-07-30 04:39 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +            zoom = 16.0
Если не переместились к локации, то и зумиться не нужно

2020-07-30 04:40 UTC, t-artikov commented on mapsdk/src/main/AndroidManifest.xml
> +        <activity android:name=".utils.permissions.PermissionActivity" />
У Activity нужно стиль задать, иначе она непрозрачная (отправлю тебе код)

2020-07-30 04:42 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/Map.kt
> +    fun disableUserLocation()
Неконстентные названия, логично было бы show/hide. При hide переставать отображать геолокацию.

2020-07-30 04:43 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +    val activity: Activity?
Если функциональность Activity не нужна, то лучше передавать Application Context. Поле лучше сделать non-nullable

2020-07-30 04:45 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +    private var locationProvider: LocationProvider? = activity?.let { LocationProvider(it) }
Лучше не создавать `LocationProvider`, пока не попросили отображение геолокации.

2020-07-30 04:46 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +                    createCircle(CircleOptions(position, 15f))
От круга точности с фейковым значением нет пользы. Лучше убрать его, а в будущем реализовать полноценно.

2020-07-30 04:55 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +        locationProvider?.requestLocation(
Детали реализации `LocationProvider` - запрос пермиссий - утекает наружу. Его интерфейс мог бы быть:
```
class LocationProvider {
    val location: StateFlow<Location?> // или какой-нибудь другой примитив, реализующий наблюдаемое значение
    fun destroy() 
}
```
`LocationProvider` сам при создании начинает запрашивать обновление `location`. Карта в `show/hideUserLocation` создает/удаляет провайдера, и при изменении его `location` обновляет маркер.

2020-07-30 05:02 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/utils/location/UserLocationOptions.kt
> +    val interval: Long? = null,
Нужно подумать о том, какие опции обновления геопозиции должны быть. Текущие завязаны на реализацию gms источника. Я бы, для начала, вообще не позволял настраивать - поставил в реализации достаточно хорошие значения. А в будущем может быть enum - высокая точность, средняя, низкая.

2020-07-30 05:07 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/utils/permissions/PermissionActivity.kt
> +        private const val TAG = "Grym/PermissionActivity"
Такого тега тут быть не должно, "Grym" - от другого приложения.

2020-07-30 05:09 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/utils/permissions/Permissions.kt
> +        context: Context, permissions: Array<String?>,
Хотелось бы чуть большей адаптации кода под Котлин, к примеру `Array<String?>` - явно должен быть `Array<String>`.

2020-07-30 05:11 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/utils/permissions/Permissions.kt
> +        var permissions = permissions
Ненужная переменная

2020-07-30 05:13 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +                    val position = LonLat(it.longitude, it.latitude)
Позицию маркера нужно обновлять при изменении геолокации, а не только первый раз.

2020-07-30 05:36 UTC, lagner requested changes

2020-07-30 05:36 UTC, lagner commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +import ru.dublgis.dgismobile.mapsdk.utils.location.UserLocationOptions
\+

2020-07-30 05:36 UTC, lagner commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +                permissionOptions = PermissionOptions(
Тут тоже плюсую. И не понятно зачем нам свой `ru.dublgis.dgismobile.mapsdk.utils.permissions`

2020-07-30 05:36 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +    val activity: Activity?
Если я правильно вижу, то тут нужен только LocationProvider. В этом случае, даже app context перебор. Нужно просить ровно то, чем пользуешься

2020-07-30 06:53 UTC, alexander-nsk commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +import ru.dublgis.dgismobile.mapsdk.utils.location.UserLocationOptions
ok

2020-07-30 06:56 UTC, alexander-nsk commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +                permissionOptions = PermissionOptions(
> Тут тоже плюсую. И не понятно зачем нам свой `ru.dublgis.dgismobile.mapsdk.utils.permissions`

Там классы для запроса разрешений вне активности/фрагмента.

2020-07-30 07:04 UTC, alexander-nsk commented on mapsdk/src/main/AndroidManifest.xml
> +        <activity android:name=".utils.permissions.PermissionActivity" />
Спасибо!

2020-07-30 08:15 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/utils/permissions/PermissionActivity.kt
> +class PermissionActivity : Activity() {
Все, что связано с пермиссиями должно быть internal

2020-07-31 11:02 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +        set(value) {
Менять то зачем позволять?

2020-07-31 11:04 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProvider.kt
> +interface LocationProvider {
Не нужно ведь во внешнем API? Управление происходит через Map. Тогда internal.

2020-07-31 11:06 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProvider.kt
> +interface LocationProvider {
Я бы ожидал такой интерфейс.
```
interface LocationProvider {
    val location: StateFlow<Location?>
    fun destroy()
}
```
И пусть он сам при конструировании запрашивает позицию.

2020-07-31 11:07 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProvider.kt
> +    @ExperimentalCoroutinesApi
Раз это экспериментальная штука, то может не стоит использовать - найти альтернативу для наблюдаемого свойства

2020-07-31 11:14 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProvider.kt
> +    val location: MutableStateFlow<Location?>
`StateFlow`, а не `MutableStateFlow` - менять снаружи нельзя

2020-07-31 11:15 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProviderFactory.kt
> +internal class LocationProviderFactory(private val activity: Activity) {
Context, а не Activity, если функциональность активити не нужна

2020-07-31 11:17 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProviderImpl.kt
> +            fastestInterval = 20000
Странно, что `fastestInterval < interval`, нужно понять какие параметры обновления является приемлимыми.

2020-07-31 11:18 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/UserLocationOptions.kt
> +    val isVisible: Boolean? = true,
Зачем nullable? Маркер Шредингера?

2020-07-31 11:19 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/UserLocationOptions.kt
> +    val interval: Long? = null,
Этот параметр и следующие не используются?

2020-07-31 11:21 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +                    options.isVisible?.let { it1 ->
Проверка на null, а не истинность. С `isVisible == false`, индикатор все равно будет отображаться.

2020-08-04 10:28 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/Map.kt
> +    val userLocation: Location?
Как думаешь будет ли полезной для пользователей возможность подписываться на изменения `userLocation`? Для этого достаточно возвращать `LiveData`.

2020-08-04 10:28 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +) : WebViewClient(), Map, LifecycleOwner {
Функциональность `LifecycleOwner` нигде не используется?

2020-08-04 10:34 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +        locationProvider?.location?.observeForever(
При свернутом приложении геолокация все равно обновляется? Не очень хорошо, в будущем стоит это исправить. Для этого и служит механизм `Lifecycle`.

2020-08-04 10:37 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/location/LocationProviderImpl.kt
> +const val LOCATION_PERMISSION_REQUEST_ID: Int = 777
internal

2020-08-04 11:17 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +    override val userLocation: LiveData<Location>?
Блин, не, не так просто. Если делать `userLocation` наблюдаемым, то оно должно быть не nullable и неизменяемым - в любой момент подписываешься и получаешь обновления.

2020-08-04 11:21 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/MapActivity.kt
> +            this.userLocation?.observe(this@MapActivity, Observer { newLocation ->
Так и задумывалось, что карта прицепляется к геолокации? Неожиданное поведение - сдвинешь карту, а она сама назад вернется. Нужно либо одиночный перелет (как было), либо отключать привязку, когда карту подвигали (сложнее).

2020-08-05 10:31 UTC, merged