CI-110 add bundle creation and signing for release pipeline
2gis/MapGL-Android pull request #41
Opened 2020-10-14 13:23 UTC by Sameri11

2020-10-14 16:29 UTC, lagner requested changes
На выходе будет круто сразу и подписанный бандл и apk, который можно поставить потестить

2020-10-14 16:29 UTC, lagner commented on ci/release.jenkinsfile
>                  archiveArtifacts(artifacts: 'build/app/outputs/apk/release/app-release-unsigned.apk')
Давай ее тоже signed сделаем. В неподписанном виде она все равно не нужна

2020-10-15 04:09 UTC, Sameri11 commented on ci/release.jenkinsfile
>                  archiveArtifacts(artifacts: 'build/app/outputs/apk/release/app-release-unsigned.apk')
Сделал подписание для apk и сохранение подписанной в артефактах

2020-10-15 12:23 UTC, lagner approved these changes

2020-10-15 12:23 UTC, lagner commented on ci/release.jenkinsfile
> +                    sh 'jarsigner -verify build/app/outputs/apk/release/app-release.apk -keystore \$RELEASE_KEYSTORE'
А в лямбду нельзя это завернуть, чтобы копипасты не было? Или там "особенности" местного groovy?

2020-10-15 12:23 UTC, merged