[SDK-245] Задание стиля карты
2gis/MapGL-Android pull request #54
Opened 2020-12-18 06:42 UTC by t-artikov

Добавлены Map.setStyle(id), Map.styleZoom
Добавлены параметры MapFragment.setup: style, styleZoom, defaultBackgroundColor, maxBounds
Добавлен пример смены стиля

2020-12-21 11:02 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformProto.kt
> +    constructor(value: String?) {
Оно же должно работать через 
```kotlin
constructor(value: Boolean?) {
```

2020-12-21 11:37 UTC, lagner requested changes

2020-12-21 11:37 UTC, lagner commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/StyleActivity.kt
> +    override fun onDGisMapReady() {
А точно надо? Мы ж ничего не делаем в ней

2020-12-21 11:37 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/LonLatBounds.kt
> +                endArray()
```kotlin
northEast.dump(writer)
```

2020-12-21 11:37 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/LonLatBounds.kt
> +                endArray()
```kotlin
southWest.dump(writer)
```

2020-12-21 11:37 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +            JsArg(null as String?)
я ниже писал, все таки не понимаю зачем так кастовать

2020-12-21 11:58 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformProto.kt
> +    constructor(value: String?) {
хочу чтобы работало
```
val value: String? = ...
val jsValue = JsValue(value)
```
и для этого сделал соответствующий конструктор,
`constructor(value: Boolean?)` не будет вызываться, параметр не такой тип имеет

2020-12-21 11:59 UTC, t-artikov commented on app/src/main/java/ru/dublgis/dgismobile/sdktestapp/StyleActivity.kt
> +    override fun onDGisMapReady() {
Лучше без нее - сделал в базовом классе ее неабстрактной, чтобы не обязательно было задавать

2020-12-21 11:59 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/LonLatBounds.kt
> +                endArray()
и то верно

2020-12-21 12:00 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/LonLatBounds.kt
> +                endArray()
сделал

2020-12-21 12:01 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformBridge.kt
> +            JsArg(null as String?)
Из-за того что я добавил `constructor(value: String?)` вызов с `null`-ом теперь неоднозначный, приходится указывать какой это `null`. Думаю, это нечастая ситуация.

2020-12-21 12:02 UTC, lagner commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformProto.kt
> +    constructor(value: String?) {
А если я сделаю `JsArg(null)` у меня же взорвется все?

2020-12-21 15:43 UTC, t-artikov commented on mapsdk/src/main/java/ru/dublgis/dgismobile/mapsdk/PlatformProto.kt
> +    constructor(value: String?) {
Да, после изменения такое перестало работать - нужно указать тип null-а. Не думаю, что критично. При необходимости можно будет добавить константу JsArg.NULL.

2020-12-22 04:01 UTC, lagner approved these changes

2020-12-22 04:10 UTC, merged