Feature sdk # move to artifactory
2gis/MapGL-Android pull request #67
Opened 2021-03-02 14:45 UTC by Sameri11

* Убираем упоминания публикаций в bintray
* Обновляем релизную CI таску
* Обновляем доку, убираем упоминания bintray

2021-05-10 15:36 UTC, lagner requested changes

2021-05-10 15:36 UTC, lagner commented on README.md
> +        url "https://maven.2gis.dev/libs-snapshot"
Почему `libs-snapshot`? Кажется надо эту часть поменять

2021-05-10 15:36 UTC, lagner commented on mapsdk/build.gradle
> +    pomName = 'mapgl'
Разве оно еще хоть где-то нужно? Зачем в общие переменные выносить?

2021-05-11 08:42 UTC, Sameri11 commented on README.md
> +        url "https://maven.2gis.dev/libs-snapshot"
Поменял на `sdk-maven-release`

2021-05-11 08:43 UTC, Sameri11 commented on mapsdk/build.gradle
> +    pomName = 'mapgl'
Посмотрел, вроде нигде не нужно.
Убрал целиком `ext` в это месте, так как было `ext -> pomConfig -> publications` - перенес все в `pomConfig`

2021-05-13 06:35 UTC, lagner approved these changes

2021-05-13 06:42 UTC, merged